# Generated by Django 5.1.5 on 2025-04-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_paid_booking_payment_intent_id_booking_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('initialized', 'Initialized'), ('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='initialized', max_length=20),
        ),
    ]
