# Generated by Django 5.1.5 on 2025-05-24 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_booking_user_booking_customer_and_more'),
        ('services', '0002_servicecategory_vehicletype_remove_service_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='addons',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='services.addonservice'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_price',
            field=models.ForeignKey(default=31, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.serviceprice'),
            preserve_default=False,
        ),
    ]
