# Generated by Django 5.1.5 on 2025-05-24 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_addons_booking_service_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='order_date',
            new_name='booking_date',
        ),
    ]
